server {
    listen 8001;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /discord {
        return 301 https://discord.gg/UZks6SHafQ;
    }
}
