services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/app/db:/app/app/db
    environment:
      - PYTHONUNBUFFERED=1
