services:
  backend:
    build:
      context: ./backend
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      # - ./backend/app:/app/app that was unnecessery with that backend dockerfile
      - ./backend/app/db:/app/app/db
      - ./images:/app/images

    environment:
      - PYTHONUNBUFFERED=1
  frontend:
    build:
      context: ./frontend
    ports:
      - "127.0.0.1:9000:80"
    # volumes:
      # - ./images:/usr/share/nginx/html/images
